/*
 * Neumo dvb (C) 2019-2024 deeptho@gmail.com
 * Copyright notice:
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#include "stackstring.h"
#include <algorithm>
#include <array>

#ifndef EXPORT
#define EXPORT __attribute__((visibility("default")))
#endif

struct lang_name_t {
	const char code[4];
	const char* name{};
};

// The following needs to be sorted according to the first argument!
static std::array lang_names{lang_name_t{"aa", "Afar"},
														 lang_name_t{"aar", "Afar"},
														 lang_name_t{"ab", "Abkhazian"},
														 lang_name_t{"abk", "Abkhazian"},
														 lang_name_t{"ace", "Achinese"},
														 lang_name_t{"ach", "Acoli"},
														 lang_name_t{"ada", "Adangme"},
														 lang_name_t{"ady", "Adyghe"},
														 lang_name_t{"ae", "Avestan"},
														 lang_name_t{"af", "Afrikaans"},
														 lang_name_t{"afa", "Afro-Asiatic"},
														 lang_name_t{"afh", "Afrihili"},
														 lang_name_t{"afr", "Afrikaans"},
														 lang_name_t{"ain", "Ainu"},
														 lang_name_t{"ak", "Akan"},
														 lang_name_t{"aka", "Akan"},
														 lang_name_t{"akk", "Akkadian"},
														 lang_name_t{"alb", "Albanian"},
														 lang_name_t{"ale", "Aleut"},
														 lang_name_t{"alg", "Algonquian"},
														 lang_name_t{"alt", "Southern Altai"},
														 lang_name_t{"am", "Amharic"},
														 lang_name_t{"amh", "Amharic"},
														 lang_name_t{"an", "Aragonese"},
														 lang_name_t{"anp", "Angika"},
														 lang_name_t{"apa", "Apache"},
														 lang_name_t{"ar", "Arabic"},
														 lang_name_t{"ara", "Arabic"},
														 lang_name_t{"arc", "Aramaic"},
														 lang_name_t{"arg", "Aragonese"},
														 lang_name_t{"arm", "Armenian"},
														 lang_name_t{"arn", "Mapudungun"},
														 lang_name_t{"arp", "Arapaho"},
														 lang_name_t{"art", "Artificial"},
														 lang_name_t{"arw", "Arawak"},
														 lang_name_t{"as", "Assamese"},
														 lang_name_t{"asm", "Assamese"},
														 lang_name_t{"ast", "Asturian"},
														 lang_name_t{"ath", "Athapascan"},
														 lang_name_t{"aus", "Australian"},
														 lang_name_t{"av", "Avaric"},
														 lang_name_t{"ava", "Avaric"},
														 lang_name_t{"ave", "Avestan"},
														 lang_name_t{"awa", "Awadhi"},
														 lang_name_t{"ay", "Aymara"},
														 lang_name_t{"aym", "Aymara"},
														 lang_name_t{"az", "Azerbaijani"},
														 lang_name_t{"aze", "Azerbaijani"},
														 lang_name_t{"ba", "Bashkir"},
														 lang_name_t{"bad", "Banda"},
														 lang_name_t{"bai", "Bamileke"},
														 lang_name_t{"bak", "Bashkir"},
														 lang_name_t{"bal", "Baluchi"},
														 lang_name_t{"bam", "Bambara"},
														 lang_name_t{"ban", "Balinese"},
														 lang_name_t{"baq", "Basque"},
														 lang_name_t{"bas", "Basa"},
														 lang_name_t{"bat", "Baltic"},
														 lang_name_t{"be", "Belarusian"},
														 lang_name_t{"bej", "Beja"},
														 lang_name_t{"bel", "Belarusian"},
														 lang_name_t{"bem", "Bemba"},
														 lang_name_t{"ben", "Bengali"},
														 lang_name_t{"ber", "Berber"},
														 lang_name_t{"bg", "Bulgarian"},
														 lang_name_t{"bh", "Bihari"},
														 lang_name_t{"bho", "Bhojpuri"},
														 lang_name_t{"bi", "Bislama"},
														 lang_name_t{"bih", "Bihari"},
														 lang_name_t{"bik", "Bikol"},
														 lang_name_t{"bin", "Bini; Edo"},
														 lang_name_t{"bis", "Bislama"},
														 lang_name_t{"bla", "Siksika"},
														 lang_name_t{"bm", "Bambara"},
														 lang_name_t{"bn", "Bengali"},
														 lang_name_t{"bnt", "Bantu"},
														 lang_name_t{"bo", "Tibetan"},
														 lang_name_t{"bod", "Tibetan"},
														 lang_name_t{"bos", "Bosnian"},
														 lang_name_t{"br", "Breton"},
														 lang_name_t{"bra", "Braj"},
														 lang_name_t{"bre", "Breton"},
														 lang_name_t{"bs", "Bosnian"},
														 lang_name_t{"btk", "Batak"},
														 lang_name_t{"bua", "Buriat"},
														 lang_name_t{"bug", "Buginese"},
														 lang_name_t{"bul", "Bulgarian"},
														 lang_name_t{"bur", "Burmese"},
														 lang_name_t{"byn", "Blin"},
														 lang_name_t{"ca", "Catalan"},
														 lang_name_t{"cad", "Caddo"},
														 lang_name_t{"cai", "Central American Indian"},
														 lang_name_t{"car", "Galibi Carib"},
														 lang_name_t{"cat", "Catalan"},
														 lang_name_t{"cau", "Caucasian"},
														 lang_name_t{"ce", "Chechen"},
														 lang_name_t{"ceb", "Cebuano"},
														 lang_name_t{"cel", "Celtic"},
														 lang_name_t{"ces", "Czech"},
														 lang_name_t{"ch", "Chamorro"},
														 lang_name_t{"cha", "Chamorro"},
														 lang_name_t{"chb", "Chibcha"},
														 lang_name_t{"che", "Chechen"},
														 lang_name_t{"chg", "Chagatai"},
														 lang_name_t{"chi", "Chinese"},
														 lang_name_t{"chk", "Chuukese"},
														 lang_name_t{"chm", "Mari"},
														 lang_name_t{"chn", "Chinook"},
														 lang_name_t{"cho", "Choctaw"},
														 lang_name_t{"chp", "Chipewyan"},
														 lang_name_t{"chr", "Cherokee"},
														 lang_name_t{"chu", "Church Slavic"},
														 lang_name_t{"chv", "Chuvash"},
														 lang_name_t{"chy", "Cheyenne"},
														 lang_name_t{"cmc", "Chamic"},
														 lang_name_t{"co", "Corsican"},
														 lang_name_t{"cop", "Coptic"},
														 lang_name_t{"cor", "Cornish"},
														 lang_name_t{"cos", "Corsican"},
														 lang_name_t{"cr", "Cree"},
														 lang_name_t{"cre", "Cree"},
														 lang_name_t{"crh", "Crimean Tatar"},
														 lang_name_t{"crp", "Creoles"},
														 lang_name_t{"cs", "Czech"},
														 lang_name_t{"csb", "Kashubian"},
														 lang_name_t{"cu", "Church Slavic"},
														 lang_name_t{"cus", "Cushitic"},
														 lang_name_t{"cv", "Chuvash"},
														 lang_name_t{"cy", "Welsh"},
														 lang_name_t{"cym", "Welsh"},
														 lang_name_t{"cze", "Czech"},
														 lang_name_t{"da", "Danish"},
														 lang_name_t{"dak", "Dakota"},
														 lang_name_t{"dan", "Danish"},
														 lang_name_t{"dar", "Dargwa"},
														 lang_name_t{"day", "Land Dayak"},
														 lang_name_t{"de", "German"},
														 lang_name_t{"del", "Delaware"},
														 lang_name_t{"den", "Slave"},
														 lang_name_t{"deu", "German"},
														 lang_name_t{"dgr", "Dogrib"},
														 lang_name_t{"din", "Dinka"},
														 lang_name_t{"div", "Divehi"},
														 lang_name_t{"doi", "Dogri"},
														 lang_name_t{"dra", "Dravidian"},
														 lang_name_t{"dsb", "Lower Sorbian"},
														 lang_name_t{"dua", "Duala"},
														 lang_name_t{"dut", "Dutch"},
														 lang_name_t{"dv", "Divehi"},
														 lang_name_t{"dyu", "Dyula"},
														 lang_name_t{"dz", "Dzongkha"},
														 lang_name_t{"dzo", "Dzongkha"},
														 lang_name_t{"ee", "Ewe"},
														 lang_name_t{"efi", "Efik"},
														 lang_name_t{"egy", "Egyptian"},
														 lang_name_t{"eka", "Ekajuk"},
														 lang_name_t{"el", "Greek"},
														 lang_name_t{"elx", "Elamite"},
														 lang_name_t{"en", "English"},
														 lang_name_t{"eng", "English"},
														 lang_name_t{"eo", "Esperanto"},
														 lang_name_t{"epo", "Esperanto"},
														 lang_name_t{"es", "Spanish"},
														 lang_name_t{"est", "Estonian"},
														 lang_name_t{"et", "Estonian"},
														 lang_name_t{"eu", "Basque"},
														 lang_name_t{"eus", "Basque"},
														 lang_name_t{"ewe", "Ewe"},
														 lang_name_t{"ewo", "Ewondo"},
														 lang_name_t{"fa", "Persian"},
														 lang_name_t{"fan", "Fang"},
														 lang_name_t{"fao", "Faroese"},
														 lang_name_t{"fas", "Persian"},
														 lang_name_t{"fat", "Fanti"},
														 lang_name_t{"ff", "Fulah"},
														 lang_name_t{"fi", "Finnish"},
														 lang_name_t{"fij", "Fijian"},
														 lang_name_t{"fil", "Filipino"},
														 lang_name_t{"fin", "Finnish"},
														 lang_name_t{"fiu", "Finno-Ugrian"},
														 lang_name_t{"fj", "Fijian"},
														 lang_name_t{"fo", "Faroese"},
														 lang_name_t{"fon", "Fon"},
														 lang_name_t{"fr", "French"},
														 lang_name_t{"fra", "French"},
														 lang_name_t{"fre", "French"},
														 lang_name_t{"frr", "Frisian"},
														 lang_name_t{"frs", "Frisian"},
														 lang_name_t{"fry", "Frisian"},
														 lang_name_t{"ful", "Fulah"},
														 lang_name_t{"fur", "Friulian"},
														 lang_name_t{"fy", "Frisian"},
														 lang_name_t{"ga", "Irish"},
														 lang_name_t{"gaa", "Ga"},
														 lang_name_t{"gay", "Gayo"},
														 lang_name_t{"gba", "Gbaya"},
														 lang_name_t{"gd", "Gaelic"},
														 lang_name_t{"gem", "German"},
														 lang_name_t{"geo", "Georgian"},
														 lang_name_t{"ger", "German"},
														 lang_name_t{"gez", "Geez"},
														 lang_name_t{"gil", "Gilbertese"},
														 lang_name_t{"gl", "Galician"},
														 lang_name_t{"gla", "Gaelic"},
														 lang_name_t{"gle", "Irish"},
														 lang_name_t{"glg", "Galician"},
														 lang_name_t{"glv", "Manx"},
														 lang_name_t{"gn", "Guarani"},
														 lang_name_t{"gon", "Gondi"},
														 lang_name_t{"gor", "Gorontalo"},
														 lang_name_t{"got", "Gothic"},
														 lang_name_t{"grb", "Grebo"},
														 lang_name_t{"gre", "Greek"},
														 lang_name_t{"grn", "Guarani"},
														 lang_name_t{"gsw", "Swiss German"},
														 lang_name_t{"gu", "Gujarati"},
														 lang_name_t{"guj", "Gujarati"},
														 lang_name_t{"gv", "Manx"},
														 lang_name_t{"gwi", "Gwich'in"},
														 lang_name_t{"ha", "Hausa"},
														 lang_name_t{"hai", "Haida"},
														 lang_name_t{"hat", "Haitian"},
														 lang_name_t{"hau", "Hausa"},
														 lang_name_t{"haw", "Hawaiian"},
														 lang_name_t{"he", "Hebrew"},
														 lang_name_t{"heb", "Hebrew"},
														 lang_name_t{"her", "Herero"},
														 lang_name_t{"hi", "Hindi"},
														 lang_name_t{"hil", "Hiligaynon"},
														 lang_name_t{"him", "Himachali"},
														 lang_name_t{"hin", "Hindi"},
														 lang_name_t{"hit", "Hittite"},
														 lang_name_t{"hmn", "Hmong; Mong"},
														 lang_name_t{"hmo", "Hiri Motu"},
														 lang_name_t{"ho", "Hiri Motu"},
														 lang_name_t{"hr", "Croatian"},
														 lang_name_t{"hrv", "Croatian"},
														 lang_name_t{"hsb", "Upper Sorbian"},
														 lang_name_t{"ht", "Haitian"},
														 lang_name_t{"hu", "Hungarian"},
														 lang_name_t{"hun", "Hungarian"},
														 lang_name_t{"hup", "Hupa"},
														 lang_name_t{"hy", "Armenian"},
														 lang_name_t{"hye", "Armenian"},
														 lang_name_t{"hz", "Herero"},
														 lang_name_t{"ia", "Interlingua"},
														 lang_name_t{"iba", "Iban"},
														 lang_name_t{"ibo", "Igbo"},
														 lang_name_t{"ice", "Icelandic"},
														 lang_name_t{"id", "Indonesian"},
														 lang_name_t{"ido", "Ido"},
														 lang_name_t{"ie", "Interlingue"},
														 lang_name_t{"ig", "Igbo"},
														 lang_name_t{"ii", "Sichuan Yi"},
														 lang_name_t{"iii", "Sichuan Yi"},
														 lang_name_t{"ijo", "Ijo"},
														 lang_name_t{"ik", "Inupiaq"},
														 lang_name_t{"iku", "Inuktitut"},
														 lang_name_t{"ile", "Interlingue"},
														 lang_name_t{"ilo", "Iloko"},
														 lang_name_t{"ina", "Interlingua"},
														 lang_name_t{"inc", "Indic"},
														 lang_name_t{"ind", "Indonesian"},
														 lang_name_t{"ine", "Indo-European"},
														 lang_name_t{"inh", "Ingush"},
														 lang_name_t{"io", "Ido"},
														 lang_name_t{"ipk", "Inupiaq"},
														 lang_name_t{"ira", "Iranian"},
														 lang_name_t{"iro", "Iroquoian"},
														 lang_name_t{"is", "Icelandic"},
														 lang_name_t{"isl", "Icelandic"},
														 lang_name_t{"it", "Italian"},
														 lang_name_t{"ita", "Italian"},
														 lang_name_t{"iu", "Inuktitut"},
														 lang_name_t{"ja", "Japanese"},
														 lang_name_t{"jav", "Javanese"},
														 lang_name_t{"jbo", "Lojban"},
														 lang_name_t{"jpn", "Japanese"},
														 lang_name_t{"jpr", "Judeo-Persian"},
														 lang_name_t{"jrb", "Judeo-Arabic"},
														 lang_name_t{"jv", "Javanese"},
														 lang_name_t{"ka", "Georgian"},
														 lang_name_t{"kaa", "Kara-Kalpak"},
														 lang_name_t{"kab", "Kabyle"},
														 lang_name_t{"kac", "Kachin; Jingpho"},
														 lang_name_t{"kal", "Kalaallisut"},
														 lang_name_t{"kam", "Kamba"},
														 lang_name_t{"kan", "Kannada"},
														 lang_name_t{"kar", "Karen"},
														 lang_name_t{"kas", "Kashmiri"},
														 lang_name_t{"kat", "Georgian"},
														 lang_name_t{"kau", "Kanuri"},
														 lang_name_t{"kaw", "Kawi"},
														 lang_name_t{"kaz", "Kazakh"},
														 lang_name_t{"kbd", "Kabardian"},
														 lang_name_t{"kg", "Kongo"},
														 lang_name_t{"kha", "Khasi"},
														 lang_name_t{"khi", "Khoisan"},
														 lang_name_t{"khm", "Central Khmer"},
														 lang_name_t{"kho", "Khotanese"},
														 lang_name_t{"ki", "Kikuyu"},
														 lang_name_t{"kik", "Kikuyu"},
														 lang_name_t{"kin", "Kinyarwanda"},
														 lang_name_t{"kir", "Kirghiz"},
														 lang_name_t{"kj", "Kuanyama"},
														 lang_name_t{"kk", "Kazakh"},
														 lang_name_t{"kl", "Kalaallisut"},
														 lang_name_t{"km", "Central Khmer"},
														 lang_name_t{"kmb", "Kimbundu"},
														 lang_name_t{"kn", "Kannada"},
														 lang_name_t{"ko", "Korean"},
														 lang_name_t{"kok", "Konkani"},
														 lang_name_t{"kom", "Komi"},
														 lang_name_t{"kon", "Kongo"},
														 lang_name_t{"kor", "Korean"},
														 lang_name_t{"kos", "Kosraean"},
														 lang_name_t{"kpe", "Kpelle"},
														 lang_name_t{"kr", "Kanuri"},
														 lang_name_t{"krc", "Karachay-Balkar"},
														 lang_name_t{"krl", "Karelian"},
														 lang_name_t{"kro", "Kru"},
														 lang_name_t{"kru", "Kurukh"},
														 lang_name_t{"ks", "Kashmiri"},
														 lang_name_t{"ku", "Kurdish"},
														 lang_name_t{"kua", "Kuanyama"},
														 lang_name_t{"kum", "Kumyk"},
														 lang_name_t{"kur", "Kurdish"},
														 lang_name_t{"kut", "Kutenai"},
														 lang_name_t{"kv", "Komi"},
														 lang_name_t{"kw", "Cornish"},
														 lang_name_t{"ky", "Kirghiz"},
														 lang_name_t{"la", "Latin"},
														 lang_name_t{"lad", "Ladino"},
														 lang_name_t{"lah", "Lahnda"},
														 lang_name_t{"lam", "Lamba"},
														 lang_name_t{"lao", "Lao"},
														 lang_name_t{"lat", "Latin"},
														 lang_name_t{"lav", "Latvian"},
														 lang_name_t{"lb", "Luxembourgish"},
														 lang_name_t{"lez", "Lezghian"},
														 lang_name_t{"lg", "Ganda"},
														 lang_name_t{"li", "Limburgan"},
														 lang_name_t{"lim", "Limburgan"},
														 lang_name_t{"lin", "Lingala"},
														 lang_name_t{"lit", "Lithuanian"},
														 lang_name_t{"ln", "Lingala"},
														 lang_name_t{"lo", "Lao"},
														 lang_name_t{"lol", "Mongo"},
														 lang_name_t{"loz", "Lozi"},
														 lang_name_t{"lt", "Lithuanian"},
														 lang_name_t{"ltz", "Luxembourgish"},
														 lang_name_t{"lu", "Luba-Katanga"},
														 lang_name_t{"lua", "Luba-Lulua"},
														 lang_name_t{"lub", "Luba-Katanga"},
														 lang_name_t{"lug", "Ganda"},
														 lang_name_t{"lui", "Luiseno"},
														 lang_name_t{"lun", "Lunda"},
														 lang_name_t{"luo", "Luo"},
														 lang_name_t{"lus", "Lushai"},
														 lang_name_t{"lv", "Latvian"},
														 lang_name_t{"mac", "Macedonian"},
														 lang_name_t{"mad", "Madurese"},
														 lang_name_t{"mag", "Magahi"},
														 lang_name_t{"mah", "Marshallese"},
														 lang_name_t{"mai", "Maithili"},
														 lang_name_t{"mak", "Makasar"},
														 lang_name_t{"mal", "Malayalam"},
														 lang_name_t{"man", "Mandingo"},
														 lang_name_t{"mao", "Maori"},
														 lang_name_t{"map", "Austronesian"},
														 lang_name_t{"mar", "Marathi"},
														 lang_name_t{"mas", "Masai"},
														 lang_name_t{"may", "Malay"},
														 lang_name_t{"mdf", "Moksha"},
														 lang_name_t{"mdr", "Mandar"},
														 lang_name_t{"men", "Mende"},
														 lang_name_t{"mg", "Malagasy"},
														 lang_name_t{"mh", "Marshallese"},
														 lang_name_t{"mi", "Maori"},
														 lang_name_t{"mic", "Mi'kmaq"},
														 lang_name_t{"min", "Minangkabau"},
														 lang_name_t{"mis", "Uncoded languages"},
														 lang_name_t{"mk", "Macedonian"},
														 lang_name_t{"mkd", "Macedonian"},
														 lang_name_t{"mkh", "Mon-Khmer"},
														 lang_name_t{"ml", "Malayalam"},
														 lang_name_t{"mlg", "Malagasy"},
														 lang_name_t{"mlt", "Maltese"},
														 lang_name_t{"mn", "Mongolian"},
														 lang_name_t{"mnc", "Manchu"},
														 lang_name_t{"mni", "Manipuri"},
														 lang_name_t{"mno", "Manobo"},
														 lang_name_t{"moh", "Mohawk"},
														 lang_name_t{"mon", "Mongolian"},
														 lang_name_t{"mos", "Mossi"},
														 lang_name_t{"mr", "Marathi"},
														 lang_name_t{"mri", "Maori"},
														 lang_name_t{"ms", "Malay"},
														 lang_name_t{"msa", "Malay"},
														 lang_name_t{"mt", "Maltese"},
														 lang_name_t{"mul", "Multiple languages"},
														 lang_name_t{"mun", "Munda"},
														 lang_name_t{"mus", "Creek"},
														 lang_name_t{"mwl", "Mirandese"},
														 lang_name_t{"mwr", "Marwari"},
														 lang_name_t{"my", "Burmese"},
														 lang_name_t{"mya", "Burmese"},
														 lang_name_t{"myn", "Mayan"},
														 lang_name_t{"myv", "Erzya"},
														 lang_name_t{"na", "Nauru"},
														 lang_name_t{"nah", "Nahuatl"},
														 lang_name_t{"nai", "North American Indian"},
														 lang_name_t{"nap", "Neapolitan"},
														 lang_name_t{"nar", "Narration"},
														 lang_name_t{"nau", "Nauru"},
														 lang_name_t{"nav", "Navajo"},
														 lang_name_t{"ndo", "Ndonga"},
														 lang_name_t{"ne", "Nepali"},
														 lang_name_t{"nep", "Nepali"},
														 lang_name_t{"new", "Nepali"},
														 lang_name_t{"ng", "Ndonga"},
														 lang_name_t{"nia", "Nias"},
														 lang_name_t{"nic", "Niger-Kordofanian"},
														 lang_name_t{"niu", "Niuean"},
														 lang_name_t{"nl", "Dutch"},
														 lang_name_t{"nld", "Dutch"},
														 lang_name_t{"no", "Norwegian"},
														 lang_name_t{"nog", "Nogai"},
														 lang_name_t{"nor", "Norwegian"},
														 lang_name_t{"nqo", "N'Ko"},
														 lang_name_t{"nso", "Pedi"},
														 lang_name_t{"nub", "Nubian"},
														 lang_name_t{"nv", "Navajo"},
														 lang_name_t{"nwc", "Classical Newari"},
														 lang_name_t{"ny", "Chichewa"},
														 lang_name_t{"nya", "Chichewa"},
														 lang_name_t{"nym", "Nyamwezi"},
														 lang_name_t{"nyn", "Nyankole"},
														 lang_name_t{"nyo", "Nyoro"},
														 lang_name_t{"nzi", "Nzima"},
														 lang_name_t{"oc", "Occitan"},
														 lang_name_t{"oci", "Occitan"},
														 lang_name_t{"oj", "Ojibwa"},
														 lang_name_t{"oji", "Ojibwa"},
														 lang_name_t{"om", "Oromo"},
														 lang_name_t{"or", "Oriya"},
														 lang_name_t{"ori", "Oriya"},
														 lang_name_t{"orm", "Oromo"},
														 lang_name_t{"os", "Ossetian"},
														 lang_name_t{"osa", "Osage"},
														 lang_name_t{"oss", "Ossetian"},
														 lang_name_t{"oth", "Other"},
														 lang_name_t{"oto", "Otomian"},
														 lang_name_t{"pa", "Panjabi"},
														 lang_name_t{"paa", "Papuan"},
														 lang_name_t{"pag", "Pangasinan"},
														 lang_name_t{"pal", "Pahlavi"},
														 lang_name_t{"pam", "Pampanga"},
														 lang_name_t{"pan", "Panjabi"},
														 lang_name_t{"pap", "Papiamento"},
														 lang_name_t{"pau", "Palauan"},
														 lang_name_t{"per", "Persian"},
														 lang_name_t{"phi", "Philippine"},
														 lang_name_t{"phn", "Phoenician"},
														 lang_name_t{"pi", "Pali"},
														 lang_name_t{"pl", "Polish"},
														 lang_name_t{"pli", "Pali"},
														 lang_name_t{"pol", "Polish"},
														 lang_name_t{"pon", "Pohnpeian"},
														 lang_name_t{"por", "Portuguese"},
														 lang_name_t{"pra", "Prakrit"},
														 lang_name_t{"ps", "Pushto"},
														 lang_name_t{"pt", "Portuguese"},
														 lang_name_t{"pus", "Pushto"},
														 lang_name_t{"qaa", "Unknown"},
														 lang_name_t{"qu", "Quechua"},
														 lang_name_t{"que", "Unknown"},
														 lang_name_t{"raj", "Rajasthani"},
														 lang_name_t{"rap", "Rapanui"},
														 lang_name_t{"rar", "Rarotongan"},
														 lang_name_t{"rm", "Romansh"},
														 lang_name_t{"rn", "Rundi"},
														 lang_name_t{"ro", "Romanian"},
														 lang_name_t{"roa", "Romance"},
														 lang_name_t{"roh", "Romansh"},
														 lang_name_t{"rom", "Romany"},
														 lang_name_t{"ron", "Romanian"},
														 lang_name_t{"ru", "Russian"},
														 lang_name_t{"rum", "Romanian"},
														 lang_name_t{"run", "Rundi"},
														 lang_name_t{"rup", "Aromanian"},
														 lang_name_t{"rus", "Russian"},
														 lang_name_t{"rw", "Kinyarwanda"},
														 lang_name_t{"sa", "Sanskrit"},
														 lang_name_t{"sad", "Sandawe"},
														 lang_name_t{"sag", "Sango"},
														 lang_name_t{"sah", "Yakut"},
														 lang_name_t{"sai", "South American Indian"},
														 lang_name_t{"sal", "Salishan languages"},
														 lang_name_t{"sam", "Samaritan Aramaic"},
														 lang_name_t{"san", "Sanskrit"},
														 lang_name_t{"sas", "Sasak"},
														 lang_name_t{"sat", "Santali"},
														 lang_name_t{"sc", "Sardinian"},
														 lang_name_t{"scn", "Sicilian"},
														 lang_name_t{"sco", "Scots"},
														 lang_name_t{"sd", "Sindhi"},
														 lang_name_t{"se", "Northern Sami"},
														 lang_name_t{"sel", "Selkup"},
														 lang_name_t{"sem", "Semitic"},
														 lang_name_t{"sg", "Sango"},
														 lang_name_t{"sgn", "Sign"},
														 lang_name_t{"shn", "Shan"},
														 lang_name_t{"si", "Sinhala"},
														 lang_name_t{"sid", "Sidamo"},
														 lang_name_t{"sin", "Sinhala"},
														 lang_name_t{"sio", "Siouan"},
														 lang_name_t{"sit", "Sino-Tibetan"},
														 lang_name_t{"sk", "Slovak"},
														 lang_name_t{"sl", "Slovenian"},
														 lang_name_t{"sla", "Slavic"},
														 lang_name_t{"slk", "Slovak"},
														 lang_name_t{"slo", "Slovak"},
														 lang_name_t{"slv", "Slovenian"},
														 lang_name_t{"sm", "Samoan"},
														 lang_name_t{"sma", "Southern Sami"},
														 lang_name_t{"sme", "Northern Sami"},
														 lang_name_t{"smi", "Sami"},
														 lang_name_t{"smj", "Lule Sami"},
														 lang_name_t{"smn", "Inari Sami"},
														 lang_name_t{"smo", "Samoan"},
														 lang_name_t{"sms", "Skolt Sami"},
														 lang_name_t{"sn", "Shona"},
														 lang_name_t{"sna", "Shona"},
														 lang_name_t{"snd", "Sindhi"},
														 lang_name_t{"snk", "Soninke"},
														 lang_name_t{"so", "Somali"},
														 lang_name_t{"sog", "Sogdian"},
														 lang_name_t{"som", "Somali"},
														 lang_name_t{"son", "Songhai"},
														 lang_name_t{"spa", "Spanish"},
														 lang_name_t{"sq", "Albanian"},
														 lang_name_t{"sqi", "Albanian"},
														 lang_name_t{"sr", "Serbian"},
														 lang_name_t{"srd", "Sardinian"},
														 lang_name_t{"srn", "Sranan Tongo"},
														 lang_name_t{"srp", "Serbian"},
														 lang_name_t{"srr", "Serer"},
														 lang_name_t{"ss", "Swati"},
														 lang_name_t{"ssa", "Nilo-Saharan"},
														 lang_name_t{"ssw", "Swati"},
														 lang_name_t{"su", "Sundanese"},
														 lang_name_t{"suk", "Sukuma"},
														 lang_name_t{"sun", "Sundanese"},
														 lang_name_t{"sus", "Susu"},
														 lang_name_t{"sux", "Sumerian"},
														 lang_name_t{"sv", "Swedish"},
														 lang_name_t{"sw", "Swahili"},
														 lang_name_t{"swa", "Swahili"},
														 lang_name_t{"swe", "Swedish"},
														 lang_name_t{"syc", "Classical Syriac"},
														 lang_name_t{"syn", "Narration"},
														 lang_name_t{"syr", "Syriac"},
														 lang_name_t{"ta", "Tamil"},
														 lang_name_t{"tah", "Tahitian"},
														 lang_name_t{"tai", "Tai"},
														 lang_name_t{"tam", "Tamil"},
														 lang_name_t{"tat", "Tatar"},
														 lang_name_t{"te", "Telugu"},
														 lang_name_t{"tel", "Telugu"},
														 lang_name_t{"tem", "Timne"},
														 lang_name_t{"ter", "Tereno"},
														 lang_name_t{"tet", "Tetum"},
														 lang_name_t{"tg", "Tajik"},
														 lang_name_t{"tgk", "Tajik"},
														 lang_name_t{"tgl", "Tagalog"},
														 lang_name_t{"th", "Thai"},
														 lang_name_t{"tha", "Thai"},
														 lang_name_t{"ti", "Tigrinya"},
														 lang_name_t{"tib", "Tibetan"},
														 lang_name_t{"tig", "Tigre"},
														 lang_name_t{"tir", "Tigrinya"},
														 lang_name_t{"tiv", "Tiv"},
														 lang_name_t{"tk", "Turkmen"},
														 lang_name_t{"tkl", "Tokelau"},
														 lang_name_t{"tl", "Tagalog"},
														 lang_name_t{"tlh", "Klingon"},
														 lang_name_t{"tli", "Tlingit"},
														 lang_name_t{"tmh", "Tamashek"},
														 lang_name_t{"tn", "Tswana"},
														 lang_name_t{"to", "Tonga"},
														 lang_name_t{"tog", "Tonga"},
														 lang_name_t{"ton", "Tonga"},
														 lang_name_t{"tpi", "Tok Pisin"},
														 lang_name_t{"tr", "Turkish"},
														 lang_name_t{"ts", "Tsonga"},
														 lang_name_t{"tsi", "Tsimshian"},
														 lang_name_t{"tsn", "Tswana"},
														 lang_name_t{"tso", "Tsonga"},
														 lang_name_t{"tt", "Tatar"},
														 lang_name_t{"tuk", "Turkmen"},
														 lang_name_t{"tum", "Tumbuka"},
														 lang_name_t{"tup", "Tupi languages"},
														 lang_name_t{"tur", "Turkish"},
														 lang_name_t{"tut", "Altaic"},
														 lang_name_t{"tvl", "Tuvalu"},
														 lang_name_t{"tw", "Twi"},
														 lang_name_t{"twi", "Twi"},
														 lang_name_t{"ty", "Tahitian"},
														 lang_name_t{"tyv", "Tuvinian"},
														 lang_name_t{"udm", "Udmurt"},
														 lang_name_t{"ug", "Uighur"},
														 lang_name_t{"uga", "Ugaritic"},
														 lang_name_t{"uig", "Uighur"},
														 lang_name_t{"uk", "Ukrainian"},
														 lang_name_t{"ukr", "Ukrainian"},
														 lang_name_t{"umb", "Umbundu"},
														 lang_name_t{"und", "Undetermined"},
														 lang_name_t{"ur", "Urdu"},
														 lang_name_t{"urd", "Urdu"},
														 lang_name_t{"uz", "Uzbek"},
														 lang_name_t{"uzb", "Uzbek"},
														 lang_name_t{"v.o", "Voice Original"},
														 lang_name_t{"vai", "Vai"},
														 lang_name_t{"ve", "Venda"},
														 lang_name_t{"ven", "Venda"},
														 lang_name_t{"vi", "Vietnamese"},
														 lang_name_t{"vie", "Vietnamese"},
														 lang_name_t{"vo", "Volapük"},
														 lang_name_t{"vol", "Volapük"},
														 lang_name_t{"vot", "Votic"},
														 lang_name_t{"wa", "Walloon"},
														 lang_name_t{"wak", "Wakashan"},
														 lang_name_t{"wal", "Wolaitta"},
														 lang_name_t{"war", "Waray"},
														 lang_name_t{"was", "Washo"},
														 lang_name_t{"wel", "Welsh"},
														 lang_name_t{"wen", "Sorbian languages"},
														 lang_name_t{"wln", "Walloon"},
														 lang_name_t{"wo", "Wolof"},
														 lang_name_t{"wol", "Wolof"},
														 lang_name_t{"xal", "Kalmyk; Oirat"},
														 lang_name_t{"xh", "Xhosa"},
														 lang_name_t{"xho", "Xhosa"},
														 lang_name_t{"yao", "Yao"},
														 lang_name_t{"yap", "Yapese"},
														 lang_name_t{"yi", "Yiddish"},
														 lang_name_t{"yid", "Yiddish"},
														 lang_name_t{"yo", "Yoruba"},
														 lang_name_t{"yor", "Yoruba"},
														 lang_name_t{"ypk", "Yupik"},
														 lang_name_t{"za", "Zhuang; Chuang"},
														 lang_name_t{"zap", "Zapotec"},
														 lang_name_t{"zbl", "Bliss"},
														 lang_name_t{"zen", "Zenaga"},
														 lang_name_t{"zh", "Chinese"},
														 lang_name_t{"zha", "Zhuang"},
														 lang_name_t{"zho", "Chinese"},
														 lang_name_t{"znd", "Zande"},
														 lang_name_t{"zu", "Zulu"},
														 lang_name_t{"zul", "Zulu"},
														 lang_name_t{"zun", "Zuni"},
														 lang_name_t{"zza", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"}};

EXPORT const char* lang_name(const char* code) {
	auto s = ss::string<4>(code).tolower();
	auto it = std::lower_bound(lang_names.begin(), lang_names.end(), s.c_str(),
														 [](const lang_name_t& a, const char* b) { return strncmp(a.code, b, 3) < 0; });
	if (it == lang_names.end())
		return "";
	if (strcmp(code, it->code) != 0)
		return "Unknown";
	return it->name;
}

EXPORT const char* lang_name(char lang1, char lang2, char lang3) {
	char code[4] = {lang1, lang2, lang3, 0};
	return lang_name(&code[0]);
}
