#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sat Jan 30 15:42:28 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import wx.richtext
from xxx import add_table
from xxx import MyGauge
from xxx import  _get_size_by_chars
# end wxGlade


class wxFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("frame")

        sizer_5 = wx.GridBagSizer(16, 16)

        label_5 = wx.StaticText(self, wx.ID_ANY, "Postioner control")
        label_5.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_5.Add(label_5, (0, 0), (1, 2), wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_5 = wx.FlexGridSizer(1, 2, 0, 32)
        sizer_5.Add(grid_sizer_5, (1, 0), (1, 2), wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, "Positioner:")
        label_1.SetToolTip("Enable posiitonir for this LNB and select control type")
        grid_sizer_5.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.choice_3 = wx.Choice(self, wx.ID_ANY, choices=["Disabled", "USALS", "DISEQC2", ""])
        self.choice_3.SetSelection(0)
        grid_sizer_5.Add(self.choice_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Drive USALS motor"), wx.VERTICAL)
        sizer_5.Add(sizer_4, (2, 0), (1, 1), wx.ALIGN_CENTER_HORIZONTAL | wx.ALL | wx.EXPAND | wx.FIXED_MINSIZE, 4)

        grid_sizer_2 = wx.GridBagSizer(4, 4)
        sizer_4.Add(grid_sizer_2, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.button_6 = wx.Button(self, wx.ID_ANY, "East")
        self.button_6.SetBitmap(wx.ArtProvider.GetBitmap(wx.ART_GO_BACK, wx.ART_OTHER, (16, 16)))
        grid_sizer_2.Add(self.button_6, (0, 0), (1, 1), 0, 0)

        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "28.2E", style=wx.TE_CENTRE)
        grid_sizer_2.Add(self.text_ctrl_2, (0, 1), (1, 1), wx.FIXED_MINSIZE, 0)

        self.button_11 = wx.Button(self, wx.ID_ANY, "West")
        self.button_11.SetBitmap(wx.ArtProvider.GetBitmap(wx.ART_GO_FORWARD, wx.ART_OTHER, (16, 16)))
        grid_sizer_2.Add(self.button_11, (0, 2), (1, 1), 0, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, "Step ")
        grid_sizer_2.Add(label_2, (1, 0), (1, 1), wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        sss= _get_size_by_chars(self.text_ctrl_2, 12,2)
        self.spin_ctrl_double_3 = wx.SpinCtrlDouble(self, wx.ID_ANY, initial=0.1, min=0.0, max=5.0, style=wx.ALIGN_CENTRE_HORIZONTAL | wx.SP_ARROW_KEYS)
        self.spin_ctrl_double_3.SetIncrement(0.05)
        self.spin_ctrl_double_3.SetDigits(2)
        #self.spin_ctrl_double_3.SetSize(sss)
        grid_sizer_2.Add(self.spin_ctrl_double_3, (1, 1), (1, 2), wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 0)

        self.button_12 = wx.Button(self, wx.ID_ANY, "Halt motor")
        grid_sizer_2.Add(self.button_12, (2, 0), (1, 3), wx.EXPAND, 0)

        self.signal_panel = wx.Panel(self, wx.ID_ANY)
        self.signal_panel.SetMinSize((400, 1))
        sizer_5.Add(self.signal_panel, (2, 1), (1, 1), wx.EXPAND, 8)

        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self.signal_panel, wx.ID_ANY, "SIgnal"), wx.HORIZONTAL)

        grid_sizer_6 = wx.FlexGridSizer(2, 3, 8, 8)
        sizer_2.Add(grid_sizer_6, 1, wx.ALL | wx.EXPAND, 8)

        label_7 = wx.StaticText(self.signal_panel, wx.ID_ANY, "RF Level")
        grid_sizer_6.Add(label_7, 0, 0, 0)

        self.gauge_1 = MyGauge(self.signal_panel, wx.ID_ANY, 100)
        grid_sizer_6.Add(self.gauge_1, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.signal_panel, wx.ID_ANY, "-48.1 dB")
        grid_sizer_6.Add(label_6, 0, wx.ALIGN_RIGHT, 0)

        label_8 = wx.StaticText(self.signal_panel, wx.ID_ANY, "SNR")
        grid_sizer_6.Add(label_8, 0, 0, 0)

        self.gauge_2 = MyGauge(self.signal_panel, wx.ID_ANY, 100)
        grid_sizer_6.Add(self.gauge_2, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.signal_panel, wx.ID_ANY, "18.1 dB")
        grid_sizer_6.Add(label_9, 0, wx.ALIGN_RIGHT, 0)

        sizer_8 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "USALS location"), wx.VERTICAL)
        sizer_5.Add(sizer_8, (3, 0), (1, 1), wx.ALIGN_CENTER_HORIZONTAL | wx.ALL | wx.EXPAND | wx.FIXED_MINSIZE, 4)

        grid_sizer_1 = wx.GridSizer(2, 3, 4, 4)
        sizer_8.Add(grid_sizer_1, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        label_3 = wx.StaticText(self, wx.ID_ANY, "Latitude")
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 0)

        self.text_ctrl_5 = wx.TextCtrl(self, wx.ID_ANY, "50.9N", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.text_ctrl_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 0)

        self.choice_2 = wx.Choice(self, wx.ID_ANY, choices=["North", "South", ""])
        self.choice_2.SetSelection(0)
        grid_sizer_1.Add(self.choice_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_4 = wx.StaticText(self, wx.ID_ANY, "Longitude")
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 0)

        self.text_ctrl_4 = wx.TextCtrl(self, wx.ID_ANY, "4.1E", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.text_ctrl_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.FIXED_MINSIZE, 8)

        self.choice_1 = wx.Choice(self, wx.ID_ANY, choices=["East", "West", ""])
        self.choice_1.SetSelection(0)
        grid_sizer_1.Add(self.choice_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_1 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Locked Mux"), wx.VERTICAL)
        sizer_5.Add(sizer_1, (3, 1), (3, 1), wx.EXPAND, 0)

        self.text_ctrl_1 =  wx.richtext.RichTextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_RICH)

        add_table(self.text_ctrl_1)
        sizer_1.Add(self.text_ctrl_1, 1, wx.EXPAND, 0)

        sizer_7 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Diseqc1.2"), wx.VERTICAL)
        sizer_5.Add(sizer_7, (4, 0), (1, 1), wx.ALIGN_CENTER_HORIZONTAL | wx.ALL | wx.EXPAND | wx.FIXED_MINSIZE, 4)

        grid_sizer_4 = wx.GridBagSizer(4, 4)
        sizer_7.Add(grid_sizer_4, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 8)

        self.button_7 = wx.Button(self, wx.ID_ANY, "Store pos.")
        self.button_7.SetBitmap(wx.ArtProvider.GetBitmap(wx.ART_GO_BACK, wx.ART_OTHER, (16, 16)))
        grid_sizer_4.Add(self.button_7, (0, 0), (1, 1), 0, 0)

        sss= _get_size_by_chars(self.text_ctrl_2, 10,2)
        self.spin_ctrl_1 = wx.SpinCtrl(self, wx.ID_ANY, "0", min=0, max=99, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        #self.spin_ctrl_1.SetSize(sss)
        grid_sizer_4.Add(self.spin_ctrl_1, (0, 1), (1, 1), wx.ALIGN_CENTER_HORIZONTAL | wx.FIXED_MINSIZE, 0)

        self.button_14 = wx.Button(self, wx.ID_ANY, "Goto pos.")
        self.button_14.SetBitmap(wx.ArtProvider.GetBitmap(wx.ART_GO_FORWARD, wx.ART_OTHER, (16, 16)))
        grid_sizer_4.Add(self.button_14, (0, 2), (1, 1), 0, 0)

        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Continuous motion and Limits"), wx.VERTICAL)
        sizer_5.Add(sizer_6, (5, 0), (1, 1), wx.ALIGN_CENTER_HORIZONTAL | wx.ALL | wx.EXPAND | wx.FIXED_MINSIZE, 4)

        grid_sizer_3 = wx.GridSizer(2, 3, 8, 8)
        sizer_6.Add(grid_sizer_3, 0, wx.ALL | wx.EXPAND, 8)

        self.button_13 = wx.Button(self, wx.ID_ANY, "Go East")
        self.button_13.SetBitmap(wx.ArtProvider.GetBitmap(wx.ART_GOTO_FIRST, wx.ART_FRAME_ICON, (16, 16)))
        grid_sizer_3.Add(self.button_13, 0, 0, 0)

        self.button_15 = wx.Button(self, wx.ID_ANY, "Go Ref")
        self.button_15.SetBitmap(wx.ArtProvider.GetBitmap(wx.ART_GO_HOME, wx.ART_FRAME_ICON, (16, 16)))
        grid_sizer_3.Add(self.button_15, 0, 0, 0)

        self.button_16 = wx.Button(self, wx.ID_ANY, "Go West")
        self.button_16.SetBitmap(wx.ArtProvider.GetBitmap(wx.ART_GOTO_LAST, wx.ART_OTHER, (16, 16)))
        grid_sizer_3.Add(self.button_16, 0, 0, 0)

        self.button_17 = wx.Button(self, wx.ID_ANY, "Set East")
        self.button_17.SetBitmap(wx.ArtProvider.GetBitmap(wx.ART_TICK_MARK, wx.ART_OTHER, (16, 16)))
        grid_sizer_3.Add(self.button_17, 0, 0, 0)

        self.button_18 = wx.Button(self, wx.ID_ANY, "Stop")
        self.button_18.SetBitmap(wx.ArtProvider.GetBitmap(wx.ART_DELETE, wx.ART_FRAME_ICON, (16, 16)))
        grid_sizer_3.Add(self.button_18, 0, 0, 0)

        self.button_19 = wx.Button(self, wx.ID_ANY, "Set West")
        self.button_19.SetBitmap(wx.ArtProvider.GetBitmap(wx.ART_TICK_MARK, wx.ART_FRAME_ICON, (16, 16)))
        grid_sizer_3.Add(self.button_19, 0, 0, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(sizer_3, (6, 0), (1, 2), wx.ALIGN_RIGHT, 0)

        self.button_3 = wx.Button(self, wx.ID_CANCEL, "")
        sizer_3.Add(self.button_3, 0, wx.ALL | wx.FIXED_MINSIZE, 8)

        self.button_2 = wx.Button(self, wx.ID_SAVE, "")
        sizer_3.Add(self.button_2, 0, wx.ALL | wx.FIXED_MINSIZE, 8)

        grid_sizer_6.AddGrowableCol(1)

        self.signal_panel.SetSizer(sizer_2)

        sizer_5.AddGrowableRow(1)
        sizer_5.AddGrowableCol(1)
        self.SetSizer(sizer_5)
        sizer_5.Fit(self)

        self.Layout()
        # end wxGlade

# end of class wxFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = wxFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
